### ISSUE TITLE
question: shouldn't the elements in the test correspond with the bucket reference with respect to number of bytes

### ISSUE THREAD

**Issue by uriva** [nazar-pc/k-bucket-sync#1]
https://github.com/nazar-pc/k-bucket-sync/blob/70cb7d7cd3947e7fd36815140462ade70baa54ea/tests/add.js#L7

just wondering, shouldn't the contact object also have 20 bytes? isn't it weird it only has one?

thanks

**Comment by nazar-pc** [comment]
It just checks that the value you put in can be found later. As the value itself is not changes, it doesn't matter what length it has.

**Comment by uriva** [comment]
but in a real world scenario, elements would be of same length of the initialization element of the bucket right?

**Comment by nazar-pc** [comment]
Yes
